GET  http://localhost:5000/app/v1/bootcamps

###

GET  http://localhost:5000/app/v1/bootcamps/2

###

POST  http://localhost:5000/app/v1/bootcamps

###

PUT http://localhost:5000/app/v1/bootcamps/2

###

DELETE http://localhost:5000/app/v1/bootcamps/5